# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('can_view', 'Can view users'), ('can_viewgroup', 'Can view groups'))},
        ),
    ]
