# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20170329_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('can_viewuser', 'Can view users'), ('can_viewgroup', 'Can view groups'), ('change_password', 'Can change_password'))},
        ),
    ]
