# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_auto_20170407_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='group',
        ),
    ]
