# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myassets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='use_default_auth',
            field=models.BooleanField(default=True, verbose_name='默认管理账号'),
        ),
    ]
